In [1]:
print("hello tito")

hello tito


In [3]:
import numpy as np

In [6]:
weigth = 185-(np.arange(5*7)/5)
print(weigth)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


In [7]:
print(weigth[5::7])

[185.  183.6 182.2 180.8 179.4]


In [1]:
import numpy as np

In [20]:
generator = np.random.default_rng(seed=80085)
scores = np.round(generator.uniform(low =30, high=100, size=15))
print(scores)

[68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


In [30]:
scores[(scores<60).nonzero()[0][:3]] = 0
scores

TypeError: '<' not supported between instances of 'list' and 'int'

In [1]:
import numpy as np

In [2]:
a = [1,2,3]
b = [4,5,6]

In [4]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [6]:
np.stack((a,b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.stack((a,b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [1]:
import numpy as np

In [2]:
print("hello world")

hello world


In [3]:
foo = np.arange(3*2*4).reshape((3,2,4))


In [4]:
print(foo)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [6]:
foo[:,:,0]

array([[ 0,  4],
       [ 8, 12],
       [16, 20]])

## lecture 2. creating numpy array

In [2]:
import numpy as np

In [3]:
sample_array = np.array([1,2,3])
sample_array 

array([1, 2, 3])

In [5]:
 ones = np.ones((2,3))

In [6]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
ones.dtype

dtype('float64')

In [8]:
zeros = np.zeros((2,3))

In [9]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [11]:
random_array = np.random.randint(0,10, size=(3,5))
random_array


array([[8, 1, 4, 7, 3],
       [5, 3, 1, 5, 8],
       [0, 7, 4, 8, 7]])

In [12]:
random_array.size

15

In [14]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.68004419, 0.11473297, 0.95387535],
       [0.92282932, 0.57957729, 0.22323998],
       [0.99374399, 0.29909923, 0.20029777],
       [0.16174032, 0.81531055, 0.32196857],
       [0.55437724, 0.21366199, 0.45952585]])

## numpy random seed

In [18]:
np.random.seed(0)
random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [19]:
np.random.seed(7)
random_array5 = np.random.random((5,3))
random_array5


array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])